version: "3.8"
services:
  backend:
    image: bkarthik7/cns_backend:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: bkarthik7/cns_frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
